# Site settings
title: Your Site Title
email: your@email.com
description: >-
  Welcome to our website. This is a brief description of what our site is about.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Navigation links
navbar_links:
  - text: Home
    url: "/"
  - text: About
    url: "/about"
  - text: Blog
    url: "/blog"
  - text: Contact
    url: "/contact"

# Social Media Links
social:
  - title: Twitter
    url: "https://twitter.com/your-twitter"
  - title: GitHub
    url: "https://github.com/your-github"
  # Add more social media links as needed

# Build settings
theme: minima
plugins:
  - jekyll-feed
