# Site settings
title: Your Awesome Website
email: your-email@example.com
description: >- # A multiline description, you can edit this
  Welcome to Your Awesome Website! Explore and discover amazing content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Navigation links
navbar_links:
  - text: Home
    url: "/"
  - text: About
    url: "/about"
  - text: Blog
    url: "/blog"
  - text: Contact
    url: "/contact"

# Social Media Links
social:
  - title: Twitter
    url: "https://twitter.com/your-twitter"
  - title: GitHub
    url: "https://github.com/your-github"
  # Add more social media links as needed

# Build settings
theme: minima
plugins:
  - jekyll-feed
