# Site settings
title: Church History
email: daramajaymarchus@gmail.com
description: >- # A multiline description, you can edit this
  "Welcome to our Church History Blog, a special place where we uncover the incredible story of our faith community throughout time. This blog is like a time machine, taking you from the earliest days of our church to the present. We'll share the amazing moments, challenges faced, and the inspiring stories that have shaped who we are today. Whether you're a long-time member or just curious, join us on this adventure through history. Each post is a chance to reflect, connect, and gain a deeper understanding of the journey that has brought us together. We're exploring the roots of our congregation, celebrating where we are now, and imagining where we're headed. Come along as we dive into the fascinating and lasting tale of our church's history!"
baseurl: "/posts" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Navigation links
navbar_links:
  - text: Home
    url: "/"
  - text: About
    url: "/about"
  - text: Blog
    url: "/blog"
  - text: Contact
    url: "/contact"
# Social Media Links
social:
  - title: Twitter
    url: "https://twitter.com/your-twitter"
  - title: GitHub
    url: "https://github.com/your-github"
  # Add more social media links as needed

# Build settings
theme: minima
plugins:
  - jekyll-feed
